general.import = ["~/.config/alacritty/theme.toml"]
general.live_config_reload = true

[cursor]
    blink_timeout = 0

    [cursor.style]
        blinking = "Never"

[mouse]
    hide_when_typing = true

[env]
    TERM = "xterm-256color"
    WINIT_X11_SCALE_FACTOR = "1.0"

[font]
    size = 15
    glyph_offset.y = 1

    [font.bold]
        family = "SF Mono"
        style = "Bold"

    [font.bold_italic]
        family = "SF Mono"
        style = "Bold Italic"

    [font.italic]
        family = "SF Mono"
        style = "Regular Italic"

    [font.normal]
        family = "SF Mono"
        style = "Regular"

[keyboard]

    [[keyboard.bindings]]
        mods = "Alt"
        key = "c"
        action = "Copy"

    [[keyboard.bindings]]
        mods = "Alt"
        key = "v"
        action = "Paste"

    [[keyboard.bindings]]
        mods = "Alt"
        key = "Escape"
        action = "ToggleViMode"

    [[keyboard.bindings]]
        mods = "Alt|Shift"
        key = "j"
        action = "DecreaseFontSize"

    [[keyboard.bindings]]
        mods = "Alt|Shift"
        key = "k"
        action = "IncreaseFontSize"

    [[keyboard.bindings]]
        mods = "Alt"
        key = "k"
        action = "ScrollLineUp"

    [[keyboard.bindings]]
        mods = "Alt"
        key = "j"
        action = "ScrollLineDown"

    [[keyboard.bindings]]
        mods = "Alt"
        key = "u"
        action = "ScrollHalfPageUp"

    [[keyboard.bindings]]
        mods = "Alt"
        key = "d"
        action = "ScrollHalfPageDown"

    [[keyboard.bindings]]
        mods = "Alt|Shift"
        key = "u"
        action = "ScrollToTop"

    [[keyboard.bindings]]
        mods = "Alt|Shift"
        key = "d"
        action = "ScrollToBottom"

    [[keyboard.bindings]]
        key = "'"
        mods = "Alt"
        command = { program = "lazygit_root" }

    [[keyboard.bindings]]
        key = "Enter"
        mods = "Alt"
        command = { program = "terminal_root" }

    [[keyboard.bindings]]
        key = "Enter"
        mods = "Shift"
        chars = "\n"

[selection]
    save_to_clipboard = true

[terminal.shell]
    program = "zsh"

[window]
    dynamic_title = true
    opacity = 1.0
    startup_mode = "Windowed"
    title = "Alacritty"

    [window.dimensions]
        columns = 120
        lines = 30

    [window.padding]
        x = 3
        y = 0

